### PR TITLE
Activating codeship

### PR DESCRIPTION
**Pull request by KatherinaFatiguso**
Hi @itinsley 
I added a space in README.md to activate the codeship.

### CODE REVIEW

**Comment by itinsley** [comment]
doesn't seem to be working. can you see codeship as a service in settings/webhooks and services?

you sure you added the correct repo when you set up codeship? You have 2 ToyRobot repos.

**Comment by KatherinaFatiguso** [comment]
Yes, it's not working. In the codeship where it's running test commands, there is an error message:

rake aborted! No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

Do I need to add something in Gemfile?

Also in ToyRobotBasic repository in Github under Settings - Webhook and Services - in the list I can see Codeship with a green tick next to it.

I have 2 repos: ToyRobot and ToyRobotBasic but I use the URL of ToyRobotBasic in codeship.

What is the rake problem here?

**Comment by KatherinaFatiguso** [comment]
I'm getting this warning in the bash terminal everytime I open the toyrobotbasic folder:

ruby-2.0.0-p598 is not installed.

To install do: 'rvm install ruby-2.0.0-p598'

Do I have to run this in terminal?

rvm install ruby-2.0.0-p598

**Comment by itinsley** [comment]
In an earlier commit I added a .ruby-version file which specifies this version. I recommend you use RVM and install this using RVM as specified in the instructions.

This is not a codeship problem. You are running rake at codeship but rake doesn't work because it hasn't been setup locally. Try running rake locally and you'll get the same error.

Once again, read the feedback. You are missing a Rakefile. Look up what a rakefile is and how to create one and add it to this branch.

Don't bother asking codeship to run anything that you haven't tested works locally!

**Comment by KatherinaFatiguso** [comment]
Hi Ian

I am getting the first green build in Codeship, how exciting!

Only the last one was a success, the first two have failed.

But the last successful build has pushed every changes from the failed builds, how interesting!

Should I just ignore those two failed or is there any way I can delete them?

[cid:4f59a94e-7f47-4a96-bc09-fb6d59935ee7]

I just discovered about what Rakefile for and how to create them in: http://rake.rubyforge.org/

First, I downloaded and install it from terminal:

$ gem install rake

Then, I created a file called 'Rakefile' and write in it:

task :default => [:test]

task :test do
  ruby "spec/toy_robot_spec.rb"
end

Is this correct, Ian?

**Comment by KatherinaFatiguso** [comment]
Hi Ian,

I tried to install the RVM but it was not successful.
When I go to toyrobotbasic directory as below, it shows the error message:

$ cd toyrobotbasic
ruby-2.0.0-p598 is not installed.
To install do: 'rvm install ruby-2.0.0-p598'
$ rvm install ruby-2.0.0-p598
Warning, new version of rvm available '1.27.0', you are using older version '1.26.11'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.0.0-p598.tar.bz2
Checking requirements for osx.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/Library/Homebrew/global.rb:3:in`<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
from /usr/local/Library/brew.rb:15:in `<main>'
ERROR: '/bin' is not writable - it is required for Homebrew, try 'brew doctor' to fix it!
Requirements installation failed with status: 1.

I searched around in Google (one reference is: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md) how to solve this problem and I tried to enter in terminal:

brew doctor

brew update

brew search

but it didn't work, with error message:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)

Do I have to uninstall and reinstall brew?
Will it affect the other projects that I am working with at the moment?

**Comment by itinsley** [comment]
I don't want to mess around with your brew setup and risk damaging your other projects. For the moment why don't you just change the version of the .ruby-version to the version of ruby you have installed locally? You can take your laptop along to one of the ruby meetups and someone will be able to help you with this. Let me know when you are going and maybe I can come along.

> But the last successful build has pushed every changes from the failed builds, how interesting!

nothing has been pushed. Codeship is passive, merely running builds based on your Master and Pull Requests branches. Only time any thing gets pushed to master is when you push it or merge a PR.

Don't worry about deleting old broken builds, they are there as a record of what happened. You get 100 free builds a month with Codeship I think which should be plenty for this project.

**Comment by KatherinaFatiguso** [comment]
I've got the first green tick from Codeship!

**Pull request merged**
